import type { Fraction, Score } from '../types/music'
import type { Clip, ClipLane, ClipDynamic, ClipHairpin, ClipOttava, ClipPedal, ClipSlur, ClipSlurPitch, ClipTempo, ClipTrill, ClipTarget } from '../utils/clip'
import { flattenRegion } from '../utils/rebar'
import { fracCreate, fracAdd, fracSub, fracCompare, fracGte, fracLt, fracToNumber } from '../utils/fraction'
import { getMeasureNotes } from '../utils/musicUtils'
import { measureCapacityFrac } from '../utils/measureCapacity'
import { formatPitch } from '../utils/pitchSpelling'
import { restShiftOverrideOf, restHiddenOf, restPositionKey, dynamicOffsetOverrideOf, noteOffsetOverrideOf, measureLeadingSpaces } from '../engine/models/engravingOverrides'
import { keyStaffId } from '../engine/models/staffContent'
import { staffMeasureView, staffIdAtIndex, staffIndexOfId } from '../engine/models/staffContent'
import { laneOfSlot, pairIsValid } from '../utils/tremoloPair'
import { staffOf, voiceOf } from '../utils/lanes'
import { slotLength } from '../utils/durations'

/**
 * A {@link Clip} plus the envelope a system clipboard needs: what produced it, where it came
 * from, and a version to guard the shape for forward-compat / OS-clipboard JSON.
 *
 * ⭐ The MUSIC is not declared here — a clip is core material (`utils/clip.ts`), and this is
 * one editor-side producer of one. Everything on `Clip` (lanes, span, dynamics, slurs, spaces)
 * is inherited verbatim; only the envelope is the clipboard's own.
 *
 * Built to grow with the selection: future element kinds (clefs, …) become their own optional
 * sections on `Clip`, dispatched on paste the same way the {@link SelectionItem} union is.
 *
 * No model ids are stored — pitches/events carry none, ties are regenerated by the
 * rebar relay on paste, and tuplets travel as atomic payloads. That is what makes
 * a payload safely re-pasteable any number of times.
 */
export interface ClipboardPayload extends Clip {
  format: 'opus-editor/clipboard'
  version: 4
  /** Where it was copied from (reference / debugging only). */
  origin: { measure: number; beat: Fraction }
  /** Number of staves the selection covered (for clamp math / UX). 1 for a single-staff clip. */
  spanStaves: number
  /** Dynamics fully inside the copy window (Phase 2) — always present on a built payload. */
  dynamics: ClipDynamic[]
  /** Slurs fully inside the copy window (Phase 3) — always present on a built payload. */
  slurs: ClipSlur[]
  /** Hairpins whose START is in the copy window — always present on a built payload. */
  hairpins: ClipHairpin[]
  /** Trills whose SIGN is inside the copy window — always present on a built payload. */
  trills: ClipTrill[]
  /**
   * Octave lines whose START is in the copy window. ⚠️ Unlike its four siblings above it is OMITTED
   * when empty (the `spaces` convention), so the `version` does not move: a payload from a score
   * with no ottava is byte-identical to a v4 one, and a reader that predates the field defaults it
   * to none — which is what it would have found anyway. Inherited from {@link Clip.ottavas}.
   */
  ottavas?: ClipOttava[]
  /** Sustain pedals whose START is in the copy window. OMITTED when empty, on the `ottavas` rule above
   *  and for its reason. Inherited from {@link Clip.pedals}. */
  pedals?: ClipPedal[]
  /** Tempo marks inside the copy window. OMITTED when empty, on the `ottavas` rule above and for
   *  its reason. Inherited from {@link Clip.tempos}. */
  tempos?: ClipTempo[]
}

/**
 * ⭐⭐ **WHICH MARKS TRAVEL — the SELECTION's answer, not the window's alone.** His report,
 * 2026-08-19, holding a Ctrl-built selection of three notes and one slur: *"i'm not selecting the
 * dynamic, however it paste it"*.
 *
 * The window says which marks a clip *may* carry (a mark half in and half out has no place in it —
 * see each builder below). This says which of those the user actually asked for. The two are an
 * INTERSECTION and the order matters: ⛔ a mark that is selected but sits outside the copied span
 * still does not travel, because the clip has no offset to file it under.
 *
 * ⚠️ Absent (`undefined`) = **everything enclosed**, which is what a caller with no selection set to
 * consult means by "copy this passage" — the rule this file had until the marks joined the
 * selection (`./enclosedMarks`). Every editor copy passes one; the specs that call the builder
 * directly do not, and they are testing the WINDOW.
 */
export type MarkFilter = (markId: string) => boolean

/** Cumulative quarter-beat offset of each measure's start, keyed by measure number. */
function measureStartOffsets(score: Score): Map<number, Fraction> {
  const out = new Map<number, Fraction>()
  let base = fracCreate(0, 1)
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    out.set(m.number, base)
    base = fracAdd(base, measureCapacityFrac(m))
  }
  return out
}

/** The sounding span [absStart, absEnd) of every selected flat note, in quarter beats. */
function selectedSpans(score: Score, noteIds: Set<string>): { start: Fraction; end: Fraction }[] {
  const starts = measureStartOffsets(score)
  const spans: { start: Fraction; end: Fraction }[] = []
  for (const m of score.measures) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const n of getMeasureNotes(m)) {
      if (!noteIds.has(n.id)) continue
      const dur = slotLength(n)
      const start = fracAdd(mStart, n.beat)
      spans.push({ start, end: fracAdd(start, dur) })
    }
  }
  return spans
}

/**
 * Manual rest shifts of one `(staff, voice)` lane whose rest onset falls inside the copy window
 * `[spanStart, spanEnd)`, as `{ offset, steps }` re-based to the window start (the same
 * basis as the lane's events). Read straight off the `Score` value via
 * `restShiftOverrideOf`. See docs/rest-shift-plan.md §6.5.
 */
function restShiftsInWindow(
  score: Score,
  staff: number,
  voice: number,
  spanStart: Fraction,
  spanEnd: Fraction,
): Array<{ offset: Fraction; steps: number }> {
  const starts = measureStartOffsets(score)
  const staffId = keyStaffId(score, staff) // this lane's staff → key segment (undefined for staff 0)
  const out: Array<{ offset: Fraction; steps: number }> = []
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const n of getMeasureNotes(m, score)) {
      if (!n.isRest || voiceOf(n) !== voice || staffOf(n) !== staff) continue
      const abs = fracAdd(mStart, n.beat)
      if (!(fracGte(abs, spanStart) && fracLt(abs, spanEnd))) continue
      const ov = restShiftOverrideOf(score, restPositionKey(m.id, voice, n.beat, staffId))
      if (!ov) continue
      out.push({ offset: fracSub(abs, spanStart), steps: ov.steps })
    }
  }
  return out
}

/**
 * Hidden rests of one `(staff, voice)` lane whose onset falls inside the copy window
 * `[spanStart, spanEnd)`, as `{ offset }` re-based to the window start (same basis as the
 * lane's events). The hidden twin of {@link restShiftsInWindow}. See docs/rest-hide-plan.md.
 */
function restHiddenInWindow(
  score: Score,
  staff: number,
  voice: number,
  spanStart: Fraction,
  spanEnd: Fraction,
): Array<{ offset: Fraction }> {
  const starts = measureStartOffsets(score)
  const staffId = keyStaffId(score, staff) // this lane's staff → key segment (undefined for staff 0)
  const out: Array<{ offset: Fraction }> = []
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const n of getMeasureNotes(m, score)) {
      if (!n.isRest || voiceOf(n) !== voice || staffOf(n) !== staff) continue
      const abs = fracAdd(mStart, n.beat)
      if (!(fracGte(abs, spanStart) && fracLt(abs, spanEnd))) continue
      if (!restHiddenOf(score, restPositionKey(m.id, voice, n.beat, staffId))) continue
      out.push({ offset: fracSub(abs, spanStart) })
    }
  }
  return out
}

/**
 * Note horizontal offsets (client #12) of one `(staff, voice)` lane whose slot onset falls inside
 * the copy window `[spanStart, spanEnd)`, as `{ offset, x }` re-based to the window start (same basis
 * as the lane's events). The chord/rest twin of {@link restShiftsInWindow} — it walks SLOTS (a note
 * offset hangs off the whole slot, chord or rest), matching the slot's own `staffId`/`voice`.
 */
function noteOffsetsInWindow(
  score: Score,
  staff: number,
  voice: number,
  spanStart: Fraction,
  spanEnd: Fraction,
): Array<{ offset: Fraction; x: number; member?: number }> {
  const starts = measureStartOffsets(score)
  const out: Array<{ offset: Fraction; x: number; member?: number }> = []
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const s of m.slots) {
      if (voiceOf(s) !== voice || staffIndexOfId(score, s.staffId) !== staff) continue
      const abs = fracAdd(mStart, s.beat)
      if (!(fracGte(abs, spanStart) && fracLt(abs, spanEnd))) continue
      const offset = fracSub(abs, spanStart)
      const ov = noteOffsetOverrideOf(score, s.id)
      if (ov && ov.x !== 0) out.push({ offset, x: ov.x })
      // ⭐ …and each fanned MEMBER's own, at the group's offset plus its place in the group. The
      // member ids on the far side are freshly minted (`cloneFanFresh`), so the index is the address
      // — safe here because a copy and its paste are one passage, in order.
      if (s.type !== 'chord' || !s.fan?.members) continue
      s.fan.members.forEach((m, k) => {
        const id = m.pitches[0]?.id
        if (!id) return
        const mov = noteOffsetOverrideOf(score, id)
        if (mov && mov.x !== 0) out.push({ offset, x: mov.x, member: k + 1 })
      })
    }
  }
  return out
}

/**
 * Two-note tremolos fully inside the copy window — the FIRST note's offset, plus its stroke style.
 *
 * "Fully" is the whole rule: a pair is a RELATION between two slots, so it travels only when BOTH
 * are in the selection. Copying just the first note copies a note, not half a mark — which is the
 * plan's own wording for what must NOT travel.
 *
 * Validated here as well as on paste, so a stale flag in the source (one that draw-time validation is
 * already refusing to draw) is never what gets copied.
 */
function tremoloPairsInWindow(
  score: Score,
  staff: number,
  voice: number,
  spanStart: Fraction,
  spanEnd: Fraction,
): Array<{ offset: Fraction; style?: 'joined' | 'open' }> {
  const starts = measureStartOffsets(score)
  const out: Array<{ offset: Fraction; style?: 'joined' | 'open' }> = []
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const slot of m.slots) {
      if (slot.type !== 'chord' || !slot.tremoloPair) continue
      if (voiceOf(slot) !== voice || staffIndexOfId(score, slot.staffId) !== staff) continue
      const lane = laneOfSlot(m.slots, slot)
      const index = lane.indexOf(slot)
      if (!pairIsValid(lane, index)) continue
      const abs = fracAdd(mStart, slot.beat)
      const partnerAbs = fracAdd(mStart, lane[index + 1].beat)
      // BOTH ends inside, or it is not a pair to copy.
      if (!(fracGte(abs, spanStart) && fracLt(partnerAbs, spanEnd))) continue
      out.push({ offset: fracSub(abs, spanStart), ...(slot.tremoloPairStyle ? { style: slot.tremoloPairStyle } : {}) })
    }
  }
  return out
}

/**
 * User-authored leading spaces (client #10) whose column falls inside the copy window
 * `[spanStart, spanEnd)`, re-based to the window start. The system-wide sibling of
 * {@link restShiftsInWindow}: no staff and no voice, because a space addresses the column.
 *
 * Read straight off the `Score` value via `measureLeadingSpaces`, so it sees every space in the
 * window whether or not the note under it happened to be selected — the selection defines a
 * musical WINDOW here, not a set of elements.
 */
function leadingSpacesInWindow(
  score: Score,
  spanStart: Fraction,
  spanEnd: Fraction,
): Array<{ offset: Fraction; space: number }> {
  const starts = measureStartOffsets(score)
  const out: Array<{ offset: Fraction; space: number }> = []
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const { beat, space } of measureLeadingSpaces(score, m.id)) {
      const abs = fracAdd(mStart, beat)
      if (!(fracGte(abs, spanStart) && fracLt(abs, spanEnd))) continue
      out.push({ offset: fracSub(abs, spanStart), space })
    }
  }
  return out
}

/**
 * The `(staff, voice)` pairs that contain at least one selected note, grouped as
 * `staff → sorted voices`. This is the lane spine: one lane per selected staff×voice.
 * `score` is threaded into getMeasureNotes so the staff projection isn't dropped.
 */
function selectedStaffVoices(score: Score, noteIds: Set<string>): Map<number, number[]> {
  const raw = new Map<number, Set<number>>()
  for (const m of score.measures) {
    for (const n of getMeasureNotes(m, score)) {
      if (!noteIds.has(n.id)) continue
      const staff = staffOf(n)
      if (!raw.has(staff)) raw.set(staff, new Set())
      raw.get(staff)!.add(voiceOf(n))
    }
  }
  const out = new Map<number, number[]>()
  for (const [staff, voices] of raw) out.set(staff, [...voices].sort((a, b) => a - b))
  return out
}

/**
 * Dynamics whose position falls FULLY inside the copy window `[spanStart, spanEnd)` and whose
 * staff is within the copied staff span `[topStaff, maxStaff]`, as {@link ClipDynamic}s with
 * the staff re-based to `topStaff` (relative) and the offset re-based to the window start.
 * Straddling / out-of-band dynamics are left behind (decision: fully-enclosed-only).
 */
function dynamicsInWindow(
  score: Score,
  topStaff: number,
  maxStaff: number,
  spanStart: Fraction,
  spanEnd: Fraction,
  wanted: MarkFilter,
): ClipDynamic[] {
  const starts = measureStartOffsets(score)
  const out: ClipDynamic[] = []
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const d of m.dynamics ?? []) {
      if (!wanted(d.id)) continue
      const abs = fracAdd(mStart, d.beat)
      if (!(fracGte(abs, spanStart) && fracLt(abs, spanEnd))) continue
      const staffIdx = staffIndexOfId(score, d.staffId)
      if (staffIdx < topStaff || staffIdx > maxStaff) continue
      const off = dynamicOffsetOverrideOf(score, d.id)
      out.push({
        staff: staffIdx - topStaff,
        // ⛔ NOT `voiceOf(d)` — that reads absent as voice 0 and would collapse a staff-wide mark
        // into a voice-1 one at COPY time, before any paste rule could save it.
        ...(d.voice !== undefined ? { voice: d.voice } : {}),
        offset: fracSub(abs, spanStart),
        text: d.text,
        ...(d.placement !== undefined ? { placement: d.placement } : {}),
        ...(off ? { engravingOffset: { x: off.x, y: off.y } } : {}),
      })
    }
  }
  return out
}

/**
 * ⭐ TEMPO MARKS inside the copy window `[spanStart, spanEnd)`, as {@link ClipTempo}s — the
 * dynamics rule (a POINT is in when its position is), minus the staff band: a tempo mark is
 * SYSTEM-level, so there is no lane to compare and no lane to re-base.
 *
 * ⚠️ That asymmetry is the reason this one takes no `topStaff`/`maxStaff`: a staff test here would
 * be a test against a field the model deliberately does not have.
 */
function temposInWindow(
  score: Score,
  spanStart: Fraction,
  spanEnd: Fraction,
  wanted: MarkFilter,
): ClipTempo[] {
  const starts = measureStartOffsets(score)
  const out: ClipTempo[] = []
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const t of m.tempos ?? []) {
      if (!wanted(t.id)) continue
      const abs = fracAdd(mStart, t.beat)
      if (!(fracGte(abs, spanStart) && fracLt(abs, spanEnd))) continue
      out.push({
        offset: fracSub(abs, spanStart),
        ...(t.text !== undefined ? { text: t.text } : {}),
        ...(t.unit !== undefined ? { unit: t.unit } : {}),
        ...(t.dots !== undefined ? { dots: t.dots } : {}),
        ...(t.bpm !== undefined ? { bpm: t.bpm } : {}),
      })
    }
  }
  return out
}

/**
 * ⭐⭐ Hairpins whose START lies in the copy window `[spanStart, spanEnd)`, on staves within the
 * copied span, as {@link ClipHairpin}s with the staff re-based to `topStaff` (relative) and the
 * start re-based to the window start. `length` is an amount of music, so it copies through
 * untouched — including past the end of the window.
 *
 * ⭐ **A SPAN BELONGS TO WHERE IT BEGINS** (2026-08-19, amending the older fully-enclosed rule after
 * his report: *"i'm including ottava and ped in the selection then copy and paste but the ottava and
 * ped does not paste"*). It is the MODEL's own filing rule — a hairpin is stored on the bar its
 * start lands in, carrying its own extent (`types/music.ts`) — and it keeps the box selection and
 * the clip saying the same thing (`interactions/enclosedMarks`).
 *
 * ⛔ Nothing is TRUNCATED, which is what the old rule guarded against: a straddling wedge travels
 * whole. ⚠️ A wedge that starts BEFORE the window is left behind — its home is that earlier music,
 * and the clip has no offset to file it under.
 */
function hairpinsInWindow(
  score: Score,
  topStaff: number,
  maxStaff: number,
  spanStart: Fraction,
  spanEnd: Fraction,
  wanted: MarkFilter,
): ClipHairpin[] {
  const starts = measureStartOffsets(score)
  const out: ClipHairpin[] = []
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const h of m.hairpins ?? []) {
      if (!wanted(h.id)) continue
      const abs = fracAdd(mStart, h.beat)
      // ⭐⭐ A SPAN BELONGS TO WHERE IT BEGINS (2026-08-19) — start inside the window, extent
      // verbatim however far past it the mark runs. See the header note on this file's builders.
      if (!fracGte(abs, spanStart) || !fracLt(abs, spanEnd)) continue
      const staffIdx = staffIndexOfId(score, h.staffId)
      if (staffIdx < topStaff || staffIdx > maxStaff) continue
      out.push({
        staff: staffIdx - topStaff,
        // The scope travels as an absence — see the dynamic's ⛔ above.
        ...(h.voice !== undefined ? { voice: h.voice } : {}),
        offset: fracSub(abs, spanStart),
        length: h.length,
        type: h.type,
        ...(h.placement !== undefined ? { placement: h.placement } : {}),
      })
    }
  }
  return out
}

/**
 * Octave lines whose START is in the copy window, as {@link ClipOttava}s — {@link hairpinsInWindow}
 * with the voice dropped (an ottava governs the staff, so it has none to record) and the same
 * inclusive end test.
 *
 * ⚠️ **Never truncated, and here that is the load-bearing half of the rule.** A cut wedge would
 * merely look wrong; a cut octave line would change the PITCH of every note past the cut, silently,
 * in the pasted copy only. So the extent travels verbatim — a 6-beat 8va copied with a 4-beat bar
 * arrives as a 6-beat 8va.
 */
function ottavasInWindow(
  score: Score,
  topStaff: number,
  maxStaff: number,
  spanStart: Fraction,
  spanEnd: Fraction,
  wanted: MarkFilter,
): ClipOttava[] {
  const starts = measureStartOffsets(score)
  const out: ClipOttava[] = []
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const o of m.ottavas ?? []) {
      if (!wanted(o.id)) continue
      const abs = fracAdd(mStart, o.beat)
      // ⭐⭐ A SPAN BELONGS TO WHERE IT BEGINS (2026-08-19) — start inside the window, extent
      // verbatim however far past it the mark runs. See the header note on this file's builders.
      if (!fracGte(abs, spanStart) || !fracLt(abs, spanEnd)) continue
      const staffIdx = staffIndexOfId(score, o.staffId)
      if (staffIdx < topStaff || staffIdx > maxStaff) continue
      out.push({ staff: staffIdx - topStaff, offset: fracSub(abs, spanStart), length: o.length, shift: o.shift })
    }
  }
  return out
}

/**
 * Sustain pedals whose START is in the copy window, as {@link ClipPedal}s — {@link ottavasInWindow}
 * with the shift dropped, since a pedal's statement is its two ends and nothing else.
 *
 * ⚠️ Its LIFT travels with it, for its own reason: a press copied without one would arrive in the
 * paste holding down whatever happens to follow it, so the copy would sustain music it never
 * covered. That is why the extent goes across verbatim rather than being cut to the window.
 */
function pedalsInWindow(
  score: Score,
  topStaff: number,
  maxStaff: number,
  spanStart: Fraction,
  spanEnd: Fraction,
  wanted: MarkFilter,
): ClipPedal[] {
  const starts = measureStartOffsets(score)
  const out: ClipPedal[] = []
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const p of m.pedals ?? []) {
      if (!wanted(p.id)) continue
      const abs = fracAdd(mStart, p.beat)
      // ⭐⭐ A SPAN BELONGS TO WHERE IT BEGINS (2026-08-19) — start inside the window, extent
      // verbatim however far past it the mark runs. See the header note on this file's builders.
      if (!fracGte(abs, spanStart) || !fracLt(abs, spanEnd)) continue
      const staffIdx = staffIndexOfId(score, p.staffId)
      if (staffIdx < topStaff || staffIdx > maxStaff) continue
      out.push({ staff: staffIdx - topStaff, offset: fracSub(abs, spanStart), length: p.length })
    }
  }
  return out
}

/**
 * Slurs with BOTH endpoints fully inside the copy window `[spanStart, spanEnd)` and on staves
 * within the copied span, as {@link ClipSlur}s: each endpoint addressed by relative staff /
 * voice / offset / pitch so paste can re-find the freshly-pasted note. A slur with an endpoint
 * outside the window is left behind (decision: fully-enclosed-only).
 */
function slursInWindow(
  score: Score,
  topStaff: number,
  maxStaff: number,
  spanStart: Fraction,
  spanEnd: Fraction,
  wanted: MarkFilter,
): ClipSlur[] {
  const slurs = score.slurs
  if (!slurs || slurs.length === 0) return []

  // Endpoint note id → its absolute onset / staff / voice / pitch (non-rest notes only).
  type EP = { abs: Fraction; staff: number; voice: number; pitch: ClipSlurPitch }
  const info = new Map<string, EP>()
  const starts = measureStartOffsets(score)
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const n of getMeasureNotes(m, score)) {
      if (n.isRest || n.step === undefined || n.octave === undefined) continue
      info.set(n.id, {
        abs: fracAdd(mStart, n.beat),
        staff: staffOf(n),
        voice: voiceOf(n),
        pitch: { step: n.step, alter: n.alter ?? 0, octave: n.octave },
      })
    }
  }

  const enclosed = (e: EP | undefined): e is EP =>
    !!e && fracGte(e.abs, spanStart) && fracLt(e.abs, spanEnd) && e.staff >= topStaff && e.staff <= maxStaff

  const out: ClipSlur[] = []
  for (const slur of slurs) {
    if (!wanted(slur.id)) continue
    const s = info.get(slur.startNoteId)
    const e = info.get(slur.endNoteId)
    if (!enclosed(s) || !enclosed(e)) continue
    out.push({
      startStaff: s.staff - topStaff, startVoice: s.voice, startOffset: fracSub(s.abs, spanStart), startPitch: s.pitch,
      endStaff: e.staff - topStaff, endVoice: e.voice, endOffset: fracSub(e.abs, spanStart), endPitch: e.pitch,
      ...(slur.placement !== undefined ? { placement: slur.placement } : {}),
    })
  }
  return out
}

/**
 * Trills whose SIGN sits inside the copy window `[spanStart, spanEnd)`, as {@link ClipTrill}s.
 *
 * ⭐ **The rule here is "the sign is enclosed", not "both ends are"** — the one place this family
 * departs from the fully-enclosed rule that dynamics, slurs and hairpins share, and deliberately.
 * Those three are shapes: half a wedge or half an arc would claim geometry the music never had, so
 * the clip leaves them behind. A trill with its end outside the window is not half a shape; it is a
 * note that is genuinely trilled, and the honest thing to carry is the trill on that note — which
 * the model already has a state for (an absent `endNoteId`). Leaving it behind would silently drop
 * an ornament from the copied music.
 */
function trillsInWindow(
  score: Score,
  topStaff: number,
  maxStaff: number,
  spanStart: Fraction,
  spanEnd: Fraction,
  wanted: MarkFilter,
): ClipTrill[] {
  const trills = score.trills
  if (!trills || trills.length === 0) return []

  type EP = { abs: Fraction; staff: number; voice: number; pitch: ClipSlurPitch }
  const info = new Map<string, EP>()
  const starts = measureStartOffsets(score)
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const n of getMeasureNotes(m, score)) {
      if (n.isRest || n.step === undefined || n.octave === undefined) continue
      info.set(n.id, {
        abs: fracAdd(mStart, n.beat),
        staff: staffOf(n),
        voice: voiceOf(n),
        pitch: { step: n.step, alter: n.alter ?? 0, octave: n.octave },
      })
    }
  }

  const enclosed = (e: EP | undefined): e is EP =>
    !!e && fracGte(e.abs, spanStart) && fracLt(e.abs, spanEnd) && e.staff >= topStaff && e.staff <= maxStaff

  const out: ClipTrill[] = []
  for (const trill of trills) {
    if (!wanted(trill.id)) continue
    const s = info.get(trill.startNoteId)
    if (!enclosed(s)) continue
    const e = trill.endNoteId !== undefined ? info.get(trill.endNoteId) : undefined
    const carryEnd = enclosed(e) && e !== s
    out.push({
      startStaff: s.staff - topStaff, startVoice: s.voice, startOffset: fracSub(s.abs, spanStart), startPitch: s.pitch,
      ...(carryEnd
        ? { endStaff: e.staff - topStaff, endVoice: e.voice, endOffset: fracSub(e.abs, spanStart), endPitch: e.pitch }
        : {}),
      ...(trill.placement !== undefined ? { placement: trill.placement } : {}),
    })
  }
  return out
}

/**
 * Build a {@link ClipboardPayload} from a note selection. Copies the contiguous
 * musical span from the first to the last selected note (so a Shift range copies
 * exactly; a scattered Ctrl selection copies the whole span between its endpoints,
 * with the in-between content included). Ties and tuplets come out correct because
 * the span is taken from {@link flattenRegion}'s event stream.
 *
 * Multi-voice AND multi-staff aware: every `(staff, voice)` lane that holds a selected note
 * is captured in its own stream (sliced to the same window), so a passage spanning voices 1
 * and 2 or staves 1 and 2 copies all of them. Staves are stored RELATIVE to the topmost
 * copied staff (0 = topmost), so a staves-1+2 clip can paste onto staves 3+4. Returns null
 * when nothing usable is selected.
 */
export function buildClipboardFromSelection(
  score: Score,
  noteIds: string[],
  markIds?: ReadonlySet<string>,
): ClipboardPayload | null {
  // ⭐ The selection filter (see {@link MarkFilter}): the marks the user is holding, intersected
  // with the marks the window can carry.
  const wanted: MarkFilter = markIds ? (id: string) => markIds.has(id) : () => true
  const idSet = new Set(noteIds)
  const spans = selectedSpans(score, idSet)
  if (spans.length === 0) return null

  const spanStart = spans.reduce((a, s) => (fracCompare(s.start, a) < 0 ? s.start : a), spans[0].start)
  const spanEnd = spans.reduce((a, s) => (fracCompare(s.end, a) > 0 ? s.end : a), spans[0].end)
  const spanBeats = fracSub(spanEnd, spanStart)

  // One lane per selected (staff, voice). Staves are re-based to the topmost selected staff so
  // the clip stores RELATIVE offsets: staff 1+2 → relStaff 0+1, paste-able onto any base staff.
  // Each lane is captured by narrowing the score to its own staff (staffMeasureView) before the
  // flatten — otherwise the per-voice flatten merges every staff's notes into one stream.
  const staffVoices = selectedStaffVoices(score, idSet)
  const staves = [...staffVoices.keys()].sort((a, b) => a - b)
  const topStaff = staves[0]
  const spanStaves = staves[staves.length - 1] - topStaff + 1

  const orderedMeasures = [...score.measures].sort((a, b) => a.number - b.number)
  const lanes: ClipLane[] = []
  for (const staff of staves) {
    const staffId = staffIdAtIndex(score, staff)
    const ordered = orderedMeasures.map((m) => staffMeasureView(m, staffId, score))
    for (const v of staffVoices.get(staff)!) {
      const restShifts = restShiftsInWindow(score, staff, v, spanStart, spanEnd)
      const restHidden = restHiddenInWindow(score, staff, v, spanStart, spanEnd)
      const noteOffsets = noteOffsetsInWindow(score, staff, v, spanStart, spanEnd)
      const tremoloPairs = tremoloPairsInWindow(score, staff, v, spanStart, spanEnd)
      lanes.push({
        staff: staff - topStaff,
        voice: v,
        // ⭐ `keepRests`: a copied REST is content the user selected and expects to see again
        //   (`utils/rebar` FlattenOptions) — the clipboard is the one caller that asks.
        events: flattenRegion(ordered, v as 0 | 1 | 2 | 3, { keepRests: true })
          .filter((e) => fracGte(e.offset, spanStart) && fracLt(e.offset, spanEnd))
          .map((e) => ({ ...e, offset: fracSub(e.offset, spanStart) })),
        // Omit each key entirely when empty (clean payload / old-clip parity).
        ...(restShifts.length ? { restShifts } : {}),
        ...(restHidden.length ? { restHidden } : {}),
        ...(noteOffsets.length ? { noteOffsets } : {}),
        ...(tremoloPairs.length ? { tremoloPairs } : {}),
      })
    }
  }
  // ⭐⭐ **SILENCE IS CONTENT.** A clip is usable when it covers real music — which a selection that
  // resolved to a span always does — and NOT when some lane happens to carry a note event. His
  // report, 2026-08-19: *"i'm able to copy a note individual and pasted it, but i cannot doit with
  // a rest"*, and the same for a group of them.
  //
  // ⚠️ `flattenRegion` deliberately drops rests (a rest is a GAP the relay regenerates), so an
  // all-rests selection produces zero events by design — and the old guard read that as "nothing
  // was selected" and refused the copy. A rest clip pastes exactly as it should through the machinery
  // that already exists: the paste keeps the destination events OUTSIDE the window, drops the ones
  // inside it, and the relay rest-fills what is left. Two beats of silence overwrite two beats.
  if (fracCompare(spanBeats, fracCreate(0, 1)) <= 0) return null

  // Dynamics (Phase 2) and slurs (Phase 3) fully inside the window travel too, staff re-based
  // to the topmost copied staff.
  const dynamics = dynamicsInWindow(score, topStaff, staves[staves.length - 1], spanStart, spanEnd, wanted)
  const slurs = slursInWindow(score, topStaff, staves[staves.length - 1], spanStart, spanEnd, wanted)
  const hairpins = hairpinsInWindow(score, topStaff, staves[staves.length - 1], spanStart, spanEnd, wanted)
  const trills = trillsInWindow(score, topStaff, staves[staves.length - 1], spanStart, spanEnd, wanted)
  const ottavas = ottavasInWindow(score, topStaff, staves[staves.length - 1], spanStart, spanEnd, wanted)
  const pedals = pedalsInWindow(score, topStaff, staves[staves.length - 1], spanStart, spanEnd, wanted)
  const tempos = temposInWindow(score, spanStart, spanEnd, wanted)
  // Authored spaces in the window travel too (client #10) — no staff re-basing, since a space
  // has no staff.
  const spaces = leadingSpacesInWindow(score, spanStart, spanEnd)

  // Origin = the (measure, beat) of the earliest selected note, for reference.
  const starts = measureStartOffsets(score)
  let origin = { measure: score.measures[0].number, beat: fracCreate(0, 1) }
  outer: for (const m of score.measures) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const n of getMeasureNotes(m)) {
      if (idSet.has(n.id) && fracCompare(fracAdd(mStart, n.beat), spanStart) === 0) {
        origin = { measure: m.number, beat: n.beat }
        break outer
      }
    }
  }

  return {
    format: 'opus-editor/clipboard', version: 4, origin, spanBeats, spanStaves, lanes, dynamics, slurs, hairpins, trills,
    // Omitted entirely when empty, matching `restShifts` (clean payload / old-clip parity).
    ...(spaces.length ? { spaces } : {}),
    ...(ottavas.length ? { ottavas } : {}),
    ...(pedals.length ? { pedals } : {}),
    ...(tempos.length ? { tempos } : {}),
  }
}

/** The (measure, beat, voice, staff) of the earliest note in a selection — literally the
 *  {@link ClipTarget} for pasting onto a selection (overwrite-forward from the selection start).
 *  The voice/staff are the paste destination for a single-voice/single-staff clip. `score` is
 *  threaded into getMeasureNotes so the staff projection isn't silently dropped (the
 *  two-projection gotcha). */
export function earliestSelectedPosition(score: Score, noteIds: string[]): ClipTarget | null {
  const idSet = new Set(noteIds)
  const starts = measureStartOffsets(score)
  let best: { measure: number; beat: Fraction; voice: number; staff: number; abs: Fraction } | null = null
  for (const m of score.measures) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const n of getMeasureNotes(m, score)) {
      if (!idSet.has(n.id)) continue
      const abs = fracAdd(mStart, n.beat)
      if (!best || fracCompare(abs, best.abs) < 0) {
        best = { measure: m.number, beat: n.beat, voice: voiceOf(n), staff: staffOf(n), abs }
      }
    }
  }
  return best ? { measure: best.measure, beat: best.beat, voice: best.voice, staff: best.staff } : null
}

/**
 * ⭐ The slot ids a paste window now holds on its destination lane — what a paste SELECTS when it
 * created no notes (a clip of pure silence: `pasteEvents` reports the chords it made, and silence
 * makes none). ⚠️ Not a general "what did the paste write": for a clip with notes the created ids
 * are the honest answer, and this would also sweep up the rest-fill after them.
 */
export function windowSlotIds(score: Score, target: ClipTarget, spanBeats: Fraction): string[] {
  const staff = target.staff ?? 0
  const ordered = [...score.measures].sort((a, b) => a.number - b.number)
  const from = ordered.findIndex(m => m.number === target.measure)
  if (from === -1) return []
  const out: string[] = []
  let remaining = spanBeats
  let start = target.beat
  for (let i = from; i < ordered.length && fracCompare(remaining, fracCreate(0, 1)) > 0; i++) {
    const m = ordered[i]
    const capacity = measureCapacityFrac(m)
    const end = fracAdd(start, remaining)
    for (const n of getMeasureNotes(m, score)) {
      if (staffOf(n) !== staff || voiceOf(n) !== target.voice) continue
      if (fracLt(n.beat, start) || fracGte(n.beat, end)) continue
      out.push(n.id)
    }
    remaining = fracSub(remaining, fracSub(capacity, start))
    start = fracCreate(0, 1)
  }
  return out
}

/** A short human-readable line for the copy/paste console dump. */
export function clipboardSummary(p: ClipboardPayload): string {
  const total = p.lanes.reduce((a, l) => a + l.events.length, 0)
  const perLane = p.lanes.map((ln) => {
    const parts = ln.events.map((e) => {
      if (e.atomic) return '[tuplet]'
      const pitches = (e.pitches ?? []).map((pt) => formatPitch(pt)).join('+')
      return `[${pitches || 'rest'} ${fracToNumber(e.duration)}b @${fracToNumber(e.offset)}]`
    })
    return `s${ln.staff}v${ln.voice + 1}: ${parts.join(' ') || '(empty)'}`
  })
  const silence = total === 0 ? ` — SILENCE (${fracToNumber(p.spanBeats)}b of rest)` : ''
  const dyn = p.dynamics.length ? `, ${p.dynamics.length} dynamic(s)` : ''
  const slr = p.slurs.length ? `, ${p.slurs.length} slur(s)` : ''
  return `${total} event(s)${silence} across ${p.lanes.length} lane(s) / ${p.spanStaves} staff(s)${dyn}${slr}, span ${fracToNumber(p.spanBeats)}b — ${perLane.join(' | ')}`
}
