import type { Fraction, Score } from '../types/music'
import type { RebarEvent } from '../utils/rebar'
import { flattenRegion } from '../utils/rebar'
import { fracCreate, fracAdd, fracSub, fracCompare, fracGte, fracLt, fracToNumber } from '../utils/fraction'
import { measureCapacityFrac, getMeasureNotes } from '../utils/musicUtils'
import { durationToFraction } from '../utils/durations'
import { restShiftOverrideOf, restHiddenOf, restPositionKey } from '../engine/models/engravingOverrides'
import { staffMeasureView, staffIdAtIndex } from '../engine/models/staffContent'

/**
 * A position-independent snapshot of copied musical material.
 *
 * Built to grow with the selection: `events` is the note/chord/tuplet section
 * (the only one today); future element kinds (dynamics, clefs, …) become their own
 * optional sections, dispatched on paste the same way the {@link SelectionItem}
 * union is. `version` guards the shape for forward-compat / OS-clipboard JSON.
 *
 * No model ids are stored — pitches/events carry none, ties are regenerated by the
 * rebar relay on paste, and tuplets travel as atomic payloads. That is what makes
 * a payload safely re-pasteable any number of times.
 */
/**
 * One copied lane: a `(staff, voice)` pair and its event stream. The staff is a
 * RELATIVE index (0 = topmost copied staff) so a clip spanning staves 1+2 can land
 * on staves 3+4 — paste adds the paste-target staff to it (payload v3, docs/copy-paste-staff-plan.md).
 */
export interface ClipboardLane {
  /** RELATIVE staff index within the clip (0 = topmost copied staff). Paste maps it to
   *  `targetStaff + staff`, clamped to the score's staff count. */
  staff: number
  /** Model voice number (0-based). */
  voice: number
  /**
   * The rhythmic stream for this lane, offsets relative to the selection start
   * (quarter beats). Internal ties are collapsed into single logical notes;
   * tuplets are atomic. Unselected gaps are implicit — rest-filled on paste.
   */
  events: RebarEvent[]
  /**
   * Manual rest shifts inside the selection window, offsets relative to the selection
   * start (same basis as {@link events}) so they re-base by the paste start. Carried
   * separately because rests are not events — a shifted rest must travel even though it
   * produces no note. Absent/empty = no shifted rests. See docs/rest-shift-plan.md §6.5.
   */
  restShifts?: Array<{ offset: Fraction; steps: number }>
  /**
   * Hidden rests inside the selection window, offsets relative to the selection start
   * (same basis as {@link events}). Carried separately for the same reason as
   * {@link restShifts} — a hidden rest produces no note but must travel. Absent/empty =
   * none hidden. See docs/rest-hide-plan.md.
   */
  restHidden?: Array<{ offset: Fraction }>
}

export interface ClipboardPayload {
  format: 'opus-editor/clipboard'
  version: 3
  /** Where it was copied from (reference / debugging only). */
  origin: { measure: number; beat: Fraction }
  /** Total covered length, in quarter-note beats. */
  spanBeats: Fraction
  /** Number of staves the selection covered (for clamp math / UX). 1 for a single-staff clip. */
  spanStaves: number
  /**
   * One entry per `(staff, voice)` lane that contained a selected note, with the staff
   * stored as a RELATIVE index (0 = topmost copied staff). A single-voice clip is
   * re-voiced into the paste target voice; a multi-voice clip preserves each voice.
   * Lanes are stored as an array (not a Map) to stay JSON-serializable.
   */
  lanes: ClipboardLane[]
  // future: dynamics?: ClipboardDynamic[]; clefs?: ClipboardClef[]; ...
}

/** Cumulative quarter-beat offset of each measure's start, keyed by measure number. */
function measureStartOffsets(score: Score): Map<number, Fraction> {
  const out = new Map<number, Fraction>()
  let base = fracCreate(0, 1)
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    out.set(m.number, base)
    base = fracAdd(base, measureCapacityFrac(m))
  }
  return out
}

/** The sounding span [absStart, absEnd) of every selected flat note, in quarter beats. */
function selectedSpans(score: Score, noteIds: Set<string>): { start: Fraction; end: Fraction }[] {
  const starts = measureStartOffsets(score)
  const spans: { start: Fraction; end: Fraction }[] = []
  for (const m of score.measures) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const n of getMeasureNotes(m)) {
      if (!noteIds.has(n.id)) continue
      const dur = n.actualDuration ?? durationToFraction(n.duration, n.dots ?? 0)
      const start = fracAdd(mStart, n.beat)
      spans.push({ start, end: fracAdd(start, dur) })
    }
  }
  return spans
}

/**
 * Manual rest shifts of one `(staff, voice)` lane whose rest onset falls inside the copy window
 * `[spanStart, spanEnd)`, as `{ offset, steps }` re-based to the window start (the same
 * basis as the lane's events). Read straight off the `Score` value via
 * `restShiftOverrideOf`. See docs/rest-shift-plan.md §6.5.
 */
function restShiftsInWindow(
  score: Score,
  staff: number,
  voice: number,
  spanStart: Fraction,
  spanEnd: Fraction,
): Array<{ offset: Fraction; steps: number }> {
  const starts = measureStartOffsets(score)
  const out: Array<{ offset: Fraction; steps: number }> = []
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const n of getMeasureNotes(m, score)) {
      if (!n.isRest || (n.voice ?? 0) !== voice || (n.staff ?? 0) !== staff) continue
      const abs = fracAdd(mStart, n.beat)
      if (!(fracGte(abs, spanStart) && fracLt(abs, spanEnd))) continue
      const ov = restShiftOverrideOf(score, restPositionKey(m.id, voice, n.beat))
      if (!ov) continue
      out.push({ offset: fracSub(abs, spanStart), steps: ov.steps })
    }
  }
  return out
}

/**
 * Hidden rests of one `(staff, voice)` lane whose onset falls inside the copy window
 * `[spanStart, spanEnd)`, as `{ offset }` re-based to the window start (same basis as the
 * lane's events). The hidden twin of {@link restShiftsInWindow}. See docs/rest-hide-plan.md.
 */
function restHiddenInWindow(
  score: Score,
  staff: number,
  voice: number,
  spanStart: Fraction,
  spanEnd: Fraction,
): Array<{ offset: Fraction }> {
  const starts = measureStartOffsets(score)
  const out: Array<{ offset: Fraction }> = []
  for (const m of [...score.measures].sort((a, b) => a.number - b.number)) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const n of getMeasureNotes(m, score)) {
      if (!n.isRest || (n.voice ?? 0) !== voice || (n.staff ?? 0) !== staff) continue
      const abs = fracAdd(mStart, n.beat)
      if (!(fracGte(abs, spanStart) && fracLt(abs, spanEnd))) continue
      if (!restHiddenOf(score, restPositionKey(m.id, voice, n.beat))) continue
      out.push({ offset: fracSub(abs, spanStart) })
    }
  }
  return out
}

/**
 * The `(staff, voice)` pairs that contain at least one selected note, grouped as
 * `staff → sorted voices`. This is the lane spine: one lane per selected staff×voice.
 * `score` is threaded into getMeasureNotes so the staff projection isn't dropped.
 */
function selectedStaffVoices(score: Score, noteIds: Set<string>): Map<number, number[]> {
  const raw = new Map<number, Set<number>>()
  for (const m of score.measures) {
    for (const n of getMeasureNotes(m, score)) {
      if (!noteIds.has(n.id)) continue
      const staff = n.staff ?? 0
      if (!raw.has(staff)) raw.set(staff, new Set())
      raw.get(staff)!.add(n.voice ?? 0)
    }
  }
  const out = new Map<number, number[]>()
  for (const [staff, voices] of raw) out.set(staff, [...voices].sort((a, b) => a - b))
  return out
}

/**
 * Build a {@link ClipboardPayload} from a note selection. Copies the contiguous
 * musical span from the first to the last selected note (so a Shift range copies
 * exactly; a scattered Ctrl selection copies the whole span between its endpoints,
 * with the in-between content included). Ties and tuplets come out correct because
 * the span is taken from {@link flattenRegion}'s event stream.
 *
 * Multi-voice AND multi-staff aware: every `(staff, voice)` lane that holds a selected note
 * is captured in its own stream (sliced to the same window), so a passage spanning voices 1
 * and 2 or staves 1 and 2 copies all of them. Staves are stored RELATIVE to the topmost
 * copied staff (0 = topmost), so a staves-1+2 clip can paste onto staves 3+4. Returns null
 * when nothing usable is selected.
 */
export function buildClipboardFromSelection(score: Score, noteIds: string[]): ClipboardPayload | null {
  const idSet = new Set(noteIds)
  const spans = selectedSpans(score, idSet)
  if (spans.length === 0) return null

  const spanStart = spans.reduce((a, s) => (fracCompare(s.start, a) < 0 ? s.start : a), spans[0].start)
  const spanEnd = spans.reduce((a, s) => (fracCompare(s.end, a) > 0 ? s.end : a), spans[0].end)
  const spanBeats = fracSub(spanEnd, spanStart)

  // One lane per selected (staff, voice). Staves are re-based to the topmost selected staff so
  // the clip stores RELATIVE offsets: staff 1+2 → relStaff 0+1, paste-able onto any base staff.
  // Each lane is captured by narrowing the score to its own staff (staffMeasureView) before the
  // flatten — otherwise the per-voice flatten merges every staff's notes into one stream.
  const staffVoices = selectedStaffVoices(score, idSet)
  const staves = [...staffVoices.keys()].sort((a, b) => a - b)
  const topStaff = staves[0]
  const spanStaves = staves[staves.length - 1] - topStaff + 1

  const orderedMeasures = [...score.measures].sort((a, b) => a.number - b.number)
  const lanes: ClipboardLane[] = []
  for (const staff of staves) {
    const staffId = staffIdAtIndex(score, staff)
    const ordered = orderedMeasures.map((m) => staffMeasureView(m, staffId, score))
    for (const v of staffVoices.get(staff)!) {
      const restShifts = restShiftsInWindow(score, staff, v, spanStart, spanEnd)
      const restHidden = restHiddenInWindow(score, staff, v, spanStart, spanEnd)
      lanes.push({
        staff: staff - topStaff,
        voice: v,
        events: flattenRegion(ordered, v as 0 | 1 | 2 | 3)
          .filter((e) => fracGte(e.offset, spanStart) && fracLt(e.offset, spanEnd))
          .map((e) => ({ ...e, offset: fracSub(e.offset, spanStart) })),
        // Omit each key entirely when empty (clean payload / old-clip parity).
        ...(restShifts.length ? { restShifts } : {}),
        ...(restHidden.length ? { restHidden } : {}),
      })
    }
  }
  // Usable if any lane carries note events OR a shifted/hidden rest (a lone one still copies).
  if (lanes.every((l) => l.events.length === 0 && !l.restShifts?.length && !l.restHidden?.length)) return null

  // Origin = the (measure, beat) of the earliest selected note, for reference.
  const starts = measureStartOffsets(score)
  let origin = { measure: score.measures[0].number, beat: fracCreate(0, 1) }
  outer: for (const m of score.measures) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const n of getMeasureNotes(m)) {
      if (idSet.has(n.id) && fracCompare(fracAdd(mStart, n.beat), spanStart) === 0) {
        origin = { measure: m.number, beat: n.beat }
        break outer
      }
    }
  }

  return { format: 'opus-editor/clipboard', version: 3, origin, spanBeats, spanStaves, lanes }
}

/** The (measure, beat, voice, staff) of the earliest note in a selection — the paste target
 *  when pasting onto a selection (overwrite-forward from the selection start). The voice/staff
 *  are the paste destination for a single-voice/single-staff clip. `score` is threaded into
 *  getMeasureNotes so the staff projection isn't silently dropped (the two-projection gotcha). */
export function earliestSelectedPosition(
  score: Score,
  noteIds: string[],
): { measure: number; beat: Fraction; voice: number; staff: number } | null {
  const idSet = new Set(noteIds)
  const starts = measureStartOffsets(score)
  let best: { measure: number; beat: Fraction; voice: number; staff: number; abs: Fraction } | null = null
  for (const m of score.measures) {
    const mStart = starts.get(m.number)
    if (!mStart) continue
    for (const n of getMeasureNotes(m, score)) {
      if (!idSet.has(n.id)) continue
      const abs = fracAdd(mStart, n.beat)
      if (!best || fracCompare(abs, best.abs) < 0) {
        best = { measure: m.number, beat: n.beat, voice: n.voice ?? 0, staff: n.staff ?? 0, abs }
      }
    }
  }
  return best ? { measure: best.measure, beat: best.beat, voice: best.voice, staff: best.staff } : null
}

/** A short human-readable line for the copy/paste console dump. */
export function clipboardSummary(p: ClipboardPayload): string {
  const total = p.lanes.reduce((a, l) => a + l.events.length, 0)
  const perLane = p.lanes.map((ln) => {
    const parts = ln.events.map((e) => {
      if (e.atomic) return '[tuplet]'
      const pitches = (e.pitches ?? []).map((pt) => {
        const acc = pt.alter === 2 ? '##' : pt.alter === 1 ? '#' : pt.alter === -1 ? 'b' : pt.alter === -2 ? 'bb' : ''
        return `${pt.step}${acc}${pt.octave}`
      }).join('+')
      return `[${pitches || 'rest'} ${fracToNumber(e.duration)}b @${fracToNumber(e.offset)}]`
    })
    return `s${ln.staff}v${ln.voice + 1}: ${parts.join(' ') || '(empty)'}`
  })
  return `${total} event(s) across ${p.lanes.length} lane(s) / ${p.spanStaves} staff(s), span ${fracToNumber(p.spanBeats)}b — ${perLane.join(' | ')}`
}
